# Generated by Django 5.1 on 2024-11-13 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='作者姓名')),
                ('introduction', models.TextField(blank=True, verbose_name='作者简介')),
                ('image', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='作者图片')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='语言代码')),
                ('name', models.CharField(max_length=50, verbose_name='语言名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '支持语言',
                'verbose_name_plural': '支持语言',
            },
        ),
        migrations.CreateModel(
            name='PoemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='类型代码')),
                ('name', models.CharField(max_length=100, verbose_name='类型名称(中文)')),
            ],
            options={
                'verbose_name': '古诗词类型',
                'verbose_name_plural': '古诗词类型',
            },
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='原文')),
                ('pinyin', models.TextField(verbose_name='拼音')),
                ('background', models.TextField(blank=True, verbose_name='创作背景')),
                ('difficulty', models.IntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=1, verbose_name='难度等级')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chinese.author', verbose_name='作者')),
                ('poem_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chinese.poemtype', verbose_name='诗词类型')),
            ],
            options={
                'verbose_name': '古诗词',
                'verbose_name_plural': '古诗词',
            },
        ),
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='译文内容')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chinese.language', verbose_name='语言')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretations', to='chinese.poem')),
            ],
            options={
                'verbose_name': '译文',
                'verbose_name_plural': '译文',
                'unique_together': {('poem', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='赏析内容')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chinese.language', verbose_name='语言')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations', to='chinese.poem')),
            ],
            options={
                'verbose_name': '赏析',
                'verbose_name_plural': '赏析',
                'unique_together': {('poem', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='注释内容')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chinese.language', verbose_name='语言')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='chinese.poem')),
            ],
            options={
                'verbose_name': '注释',
                'verbose_name_plural': '注释',
                'unique_together': {('poem', 'language')},
            },
        ),
    ]
