# Generated by Django 5.1 on 2024-11-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='title_pinyin',
            field=models.CharField(blank=True, max_length=200, verbose_name='标题拼音'),
        ),
    ]
