# Generated by Django 5.1 on 2024-11-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0002_poem_title_pinyin'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpretation',
            name='title_translation',
            field=models.CharField(blank=True, max_length=200, verbose_name='标题译文'),
        ),
    ]
