# Generated by Django 5.1 on 2024-11-13 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0003_interpretation_title_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoemGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='体裁代码')),
                ('name', models.CharField(max_length=100, verbose_name='体裁名称')),
                ('description', models.TextField(blank=True, verbose_name='体裁说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '诗歌体裁',
                'verbose_name_plural': '诗歌体裁',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PoemGenreRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poem_relations', to='chinese.poemgenre', verbose_name='体裁')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_relations', to='chinese.poem', verbose_name='诗歌')),
            ],
            options={
                'verbose_name': '诗歌体裁关系',
                'verbose_name_plural': '诗歌体裁关系',
                'ordering': ['created_at'],
                'unique_together': {('poem', 'genre')},
            },
        ),
    ]
