# Generated by Django 5.1 on 2024-11-17 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0004_poemgenre_poemgenrerelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='introduction',
        ),
        migrations.AddField(
            model_name='author',
            name='name_pinyin',
            field=models.CharField(blank=True, max_length=100, verbose_name='作者拼音'),
        ),
        migrations.CreateModel(
            name='AuthorIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='作者介绍')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='introductions', to='chinese.author', verbose_name='作者')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chinese.language', verbose_name='语言')),
            ],
            options={
                'verbose_name': '作者介绍',
                'verbose_name_plural': '作者介绍',
                'unique_together': {('author', 'language')},
            },
        ),
    ]
