# Generated by Django 5.1 on 2024-11-17 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0005_remove_author_introduction_author_name_pinyin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretation',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretations', to='chinese.poem', verbose_name='诗词'),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='title_translation',
            field=models.CharField(blank=True, max_length=1000, verbose_name='标题译文'),
        ),
    ]
