# Generated by Django 5.1 on 2024-11-24 10:07

import chinese.models.author
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0006_alter_interpretation_poem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='poems/images/', verbose_name='诗词配图'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=chinese.models.author.author_image_path),
        ),
    ]
