# Generated by Django 5.1 on 2024-11-24 10:19

import chinese.models.poem
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0007_poem_image_alter_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=chinese.models.poem.poem_image_path, verbose_name='诗词配图'),
        ),
    ]
