# Generated by Django 5.1 on 2024-11-27 04:39

import chinese.models.font_info
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0008_alter_poem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='分类代码')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类说明')),
                ('order', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '字体分类',
                'verbose_name_plural': '字体分类',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FontInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='字体名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='字体代码')),
                ('file', models.FileField(upload_to=chinese.models.font_info.font_file_path, verbose_name='字体文件')),
                ('preview_image', models.ImageField(blank=True, help_text='建议上传包含常用汉字的预览图片', null=True, upload_to=chinese.models.font_info.font_preview_path, verbose_name='字体预览图')),
                ('description', models.TextField(blank=True, verbose_name='字体说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonts', to='chinese.fontcategory', verbose_name='字体分类')),
            ],
            options={
                'verbose_name': '字体',
                'verbose_name_plural': '字体',
                'ordering': ['category', 'code'],
            },
        ),
    ]
