# Generated by Django 5.1 on 2024-12-05 04:57

import chinese.models.poem
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0010_imagecategory_imageinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='用于展示页面顶部的横幅图片，建议尺寸 1920x480', null=True, upload_to=chinese.models.poem.poem_image_path, verbose_name='横幅图片'),
        ),
        migrations.AddField(
            model_name='poem',
            name='excerpt',
            field=models.TextField(blank=True, help_text='诗词中的经典名句或精彩片段', verbose_name='摘录'),
        ),
    ]
