# Generated by Django 5.1 on 2024-12-06 03:52

import chinese.models.image_info
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0011_poem_banner_image_poem_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageinfo',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=chinese.models.image_info.thumbnail_upload_path, verbose_name='缩略图'),
        ),
    ]
