# Generated by Django 5.1 on 2024-12-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese', '0012_imageinfo_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='audio_url',
            field=models.URLField(blank=True, help_text='诗词朗诵的音频链接，支持mp3格式', max_length=500, null=True, verbose_name='朗诵音频'),
        ),
    ]
